# theme: minimal-mistakes-jekyll
remote_theme: pages-themes/minimal@v0.2.0

# Site settings
title: Privacy Policy
description: This is privacy policy for the application.

# GitHub Pages settings
github:
  is_project_page: false

# Plugins (if needed, for additional Jekyll functionality)
plugins:
  - jekyll-feed
  - jekyll-remote-theme
