theme: "just-the-docs"
remote_theme: pmarsceill/just-the-docs

# Site settings
title: [Your Site Name]
description: [A brief description of your site's purpose]

# GitHub Pages settings
github:
  is_project_page: false

# Plugins (if needed, for additional Jekyll functionality)
plugins:
  - jekyll-feed
